[package]
name = "freya-hn-app"
version = "0.1.0"
edition = "2021"

[dependencies]
freya = "0.3"
dioxus = { version = "0.6", features = [
  "macro",
  "hooks",
], default-features = false }
jiff = { version = "0.2", features = ["serde"] }
once_cell = "1.21.3"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
