version: "3"
env:
  PGM_NAME: freya-hn-app
tasks:
  build:
    deps: [fmt, clippy]
    cmds:
      - cargo build --release
  clippy:
    cmds:
      - cargo clippy
  fmt:
    cmds:
      - cargo fmt
  loc:
    cmds:
      - tokei . --exclude vendor
  run:
    deps: [build]
    cmds:
      - target/release/$PGM_NAME
  run:debug:
    deps: [build]
    cmds:
      - FREYA_DEBUG=1 target/release/$PGM_NAME
  typo:
    cmds:
      - typos src/**/*.rs
  typo:fix:
    cmds:
      - typos -w src/**/*.rs
