# .github/workflows/release.yml

name: Create Release Build

# This workflow triggers when a new tag starting with 'v' is pushed.
on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    name: Create Release for ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # Step 1: Check out the repository code.
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the specified Rust toolchain.
      - name: Set up Rust 1.87.0
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.87.0

      # NEW: Step 3: Cache Cargo dependencies for faster builds.
      # This will reuse downloaded and compiled dependencies from previous runs.
      - name: Cache Cargo Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Step 4: Install platform-specific dependencies required for Freya.
      - name: Install System Dependencies
        run: |
          # Linux (Ubuntu) requires several development libraries for rendering and windowing.
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y \
              pkg-config \
              libssl-dev \
              libglib2.0-dev \
              libcairo2-dev \
              libgtk-3-dev \
              libgdk-pixbuf2.0-dev \
              libwebkit2gtk-4.1-dev \
              libayatana-appindicator3-dev
          fi
        shell: bash

      # Step 5: Build the application in release mode.
      - name: Build Application
        run: cargo build --release

      # Step 6: Prepare the artifact for upload.
      - name: Prepare Artifact
        run: |
          # Set the path and name for the final binary based on the OS.
          if [ "$RUNNER_OS" == "Linux" ]; then
            ARTIFACT_PATH="target/release/freya-hn-app"
            ARTIFACT_NAME="freya-hn-app-linux"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            ARTIFACT_PATH="target/release/freya-hn-app"
            ARTIFACT_NAME="freya-hn-app-macos"
          elif [ "$RUNNER_OS" == "Windows" ]; then
            ARTIFACT_PATH="target/release/freya-hn-app.exe"
            ARTIFACT_NAME="freya-hn-app-windows.exe"
          fi
          # Use GITHUB_ENV to make these variables available to the next step.
          echo "ARTIFACT_PATH=${ARTIFACT_PATH}" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV
        shell: bash

      # Step 7: Upload the compiled binary as a workflow artifact.
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
